apiVersion: v1
kind: Service
metadata:
  name: imdb-sentiment-service
spec:
  type: NodePort
  selector:
    app: imdb-sentiment
  ports:
    - protocol: TCP
      port: 8000       # Port on the service itself
      targetPort: 8000 # Port on the container
      nodePort: 30007  # Port on the localhost (Minikube will map this to localhost:30007)
