name: Continuous Integration

on:
  push:
    branches: [main, feature/testing-ci]
  pull_request:
    branches: [main, feature/testing-ci]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step to download the model artifact if it exists
    - name: Download sentiment model artifact
      uses: actions/download-artifact@v3
      with:
        name: sentiment_model
        path: .

    # Step to train the model if it is not already present
    - name: Train model if missing
      run: |
        if [ ! -f sentiment_model.keras ]; then
          python train_model.py
        fi

    - name: Run Tests with Coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage xml  # Generate a report in XML format

    - name: Upload Coverage to GitHub
      uses: codecov/codecov-action@v2  # Using Codecov for GitHub integration
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

    # Upload the model artifact for future workflow runs
    - name: Upload sentiment model artifact
      if: success() && always()  # Ensures upload after a successful run
      uses: actions/upload-artifact@v3
      with:
        name: sentiment_model
        path: sentiment_model.keras
