name: Continuous Integration

on:
  push:
    branches: [main, feature/testing-ci]
  pull_request:
    branches: [main, feature/testing-ci]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v4  # Updated to v4 for latest support

    - name: Setup Python 3.10
      uses: actions/setup-python@v4  # Ensure latest supported version
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests with Coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3  # Updated to v3 for Node 16/20 support
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
