name: Continuous Integration

on:
  push:
    branches: [main, feature/testing-ci]
  pull_request:
    branches: [main, feature/testing-ci]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests with Coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage xml  # Generate a report in XML format

    - name: Upload Coverage to GitHub
      uses: codecov/codecov-action@v2  # Using Codecov for GitHub integration
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
