name: Continuous Integration

on:
  push:
    branches: [main, testing-ci]
  pull_request:
    branches: [main, testing-ci]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check for and Download Model Artifact
      id: download-model
      uses: actions/download-artifact@v3
      with:
        name: sentiment_model
        path: ./
      continue-on-error: true  # Allow the workflow to continue even if download fails

    - name: Train Model (if artifact missing)
      if: steps.download-model.outcome == 'failure'
      run: |
        echo "Model artifact not found. Training the model..."
        python train_model.py

    - name: Upload Model Artifact
      if: steps.download-model.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: sentiment_model
        path: sentiment_model.keras

    - name: Run Tests with Coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
    