name: Continuous Integration

on:
  push:
    branches: [main, feature/testing-ci]
  pull_request:
    branches: [main, feature/testing-ci]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download Model Artifact
      uses: actions/download-artifact@v3
      with:
        name: sentiment_model
        path: ./

    - name: Verify Model Existence
      run: |
        if [ ! -f "sentiment_model.keras" ]; then
          echo "Model file not found! Training model as a backup."
          python train_model.py  # Re-train if model is missing
        fi

    - name: Run Tests with Coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage xml

    - name: Upload Coverage to GitHub
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
